name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v4
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm clean-install
      - name: Build and test
        run: |
          rm -rf dist
          npx nx run-many --target=build --all --parallel=2
          npx nx run-many --target=test --ci --all --parallel=2
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          git config user.name "Release Bot"
          git config user.email "<>"
          npx nx release --yes
