name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        name: Setup Node.js
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: |
          rm -rf dist
          npx nx run-many --target=build --all --parallel=2
          npx nx run-many --target=test --ci --all --parallel=2
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "Release Bot"
          git config user.email "<>"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          npx lerna publish --yes --create-release github
